services:
  nginx-rtmp:
    build: .
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # Health check
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3 